import { BellRing, DatabaseBackup, Download, Keyboard, MonitorCog, Palette, Plus, Upload, Users } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { PageHeader } from "../../components/app-shell";
import { Button, Dialog, EmptyState, Field, Input, Select } from "../../components/ui";
import { DEFAULT_SETTINGS } from "@shared/constants/defaults";
import { contentRepository, type ReferenceEntity, type ReferenceKind } from "../../services/content-repository";
import { useUIStore } from "../../stores/ui-store";
import type { AppSettings, ContentPillar, ContentType, Platform, Tag } from "@shared/types/domain";
import { useWorkspace } from "../../hooks/use-workspace";
import { useAuth } from "../../hooks/use-auth-context";
import { authService } from "../../services/auth-service";
import type { AccountStatus, CreateUserInput, DataScope, RoleKey, SafeUser } from "@shared/types/auth";

export function SettingsPage() {
  const workspace = useWorkspace(); const { setTheme, pushToast } = useUIStore(); const [settings, setSettings] = useState<AppSettings>(DEFAULT_SETTINGS); const [loaded, setLoaded] = useState(false); const [managerOpen, setManagerOpen] = useState(false); const input = useRef<HTMLInputElement>(null); const queryClient = useQueryClient();
  const { hasPermission } = useAuth();
  useEffect(() => { void contentRepository.getSettings().then((value) => { if (value) { setSettings(value); setTheme(value.theme); } setLoaded(true); }); }, [setTheme]);
  if (workspace.isLoading || !loaded) return <div className="page"><div className="skeleton heading-skeleton" /><div className="skeleton panel-skeleton" /></div>;
  if (!workspace.data) return <div className="page"><EmptyState title="تنظیمات در دسترس نیست" description="فضای کاری را دوباره باز کنید." /></div>;
  const update = (next: Partial<AppSettings>) => { const merged = { ...settings, ...next }; setSettings(merged); if (next.theme) setTheme(next.theme); void contentRepository.saveSettings(merged).then(() => pushToast({ title: "تنظیمات ذخیره شد." })).catch(() => pushToast({ title: "ذخیره تنظیمات ممکن نشد." })); };
  const exportData = async () => { const raw = await contentRepository.exportWorkspace(); saveFile("rooznegar-export.json", raw, "application/json"); pushToast({ title: "فایل خروجی آماده شد." }); };
  const backup = async () => { const raw = await contentRepository.backup(); saveFile(`rooznegar-backup-${new Date().toISOString().slice(0, 10)}.json`, raw, "application/json"); pushToast({ title: "پشتیبان محلی ساخته شد." }); };
  const importData = async (file?: File) => { if (!file) return; const result = await contentRepository.importWorkspace(await file.text()); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); await queryClient.invalidateQueries({ queryKey: ["contents"] }); pushToast({ title: result.errors.length ? `ورود با ${result.errors.length.toLocaleString("fa-IR")} خطا تمام شد.` : `${result.imported.toLocaleString("fa-IR")} رکورد وارد شد.` }); };
  return <div className="page settings-page"><PageHeader title="تنظیمات" description="ظاهر، رفتار تقویم و حفاظت از داده های محلی را مدیریت کنید." />
    <div className="settings-grid"><section className="surface settings-section"><header><Palette size={20} /><div><h2>نمایش</h2><p>ظاهر برنامه را برای محیط کار خود تنظیم کنید.</p></div></header><div className="settings-form"><Field label="تم"><Select value={settings.theme} onChange={(event) => update({ theme: event.target.value as AppSettings["theme"] })}><option value="light">روشن</option><option value="dark">تاریک</option><option value="system">مطابق سیستم</option></Select></Field><Field label="اعداد"><Select value={settings.numeralSystem} onChange={(event) => update({ numeralSystem: event.target.value as AppSettings["numeralSystem"] })}><option value="persian">فارسی</option><option value="english">انگلیسی</option></Select></Field><Field label="نمای پیش فرض تقویم"><Select value={settings.defaultCalendarView} onChange={(event) => update({ defaultCalendarView: event.target.value as AppSettings["defaultCalendarView"] })}><option value="month">ماه</option><option value="week">هفته</option><option value="day">روز</option><option value="agenda">فهرست</option></Select></Field></div></section>
      <section className="surface settings-section"><header><BellRing size={20} /><div><h2>یادآوری</h2><p>فقط پس از رضایت شما، یادآوری های محلی فعال می شوند.</p></div></header><div className="settings-form"><label className="switch-row"><span><strong>فعال سازی اعلان ها</strong><small>یادآوری انتشار و بررسی</small></span><input type="checkbox" checked={settings.notificationsEnabled} onChange={(event) => update({ notificationsEnabled: event.target.checked })} /></label><Field label="مدت پیش از انتشار"><Select value={String(settings.notificationLeadMinutes)} disabled={!settings.notificationsEnabled} onChange={(event) => update({ notificationLeadMinutes: Number(event.target.value) })}><option value="15">۱۵ دقیقه</option><option value="30">۳۰ دقیقه</option><option value="60">۱ ساعت</option><option value="120">۲ ساعت</option></Select></Field></div></section>
      <section className="surface settings-section"><header><DatabaseBackup size={20} /><div><h2>پشتیبان و داده</h2><p>داده ها فقط روی دستگاه شما می مانند. پشتیبان منظم را فراموش نکنید.</p></div></header><div className="settings-actions"><Button variant="secondary" onClick={() => void backup()}><DatabaseBackup size={17} />ساخت پشتیبان</Button><Button variant="secondary" onClick={() => void exportData()}><Download size={17} />خروجی JSON</Button><Button variant="secondary" onClick={() => input.current?.click()}><Upload size={17} />ورود فایل</Button><input ref={input} type="file" accept="application/json,.json" hidden onChange={(event) => void importData(event.target.files?.[0])} /></div></section>
      <section className="surface settings-section"><header><MonitorCog size={20} /><div><h2>داده های مرجع</h2><p>نام و رنگ پلتفرم ها، نوع ها، ستون ها و برچسب ها را متناسب با تیم خود تنظیم کنید.</p></div></header><Button variant="secondary" onClick={() => setManagerOpen(true)}><Plus size={17} />مدیریت داده های مرجع</Button></section>
      {hasPermission("users.view") && <UserManagementPanel />}
      <section className="surface settings-section"><header><Keyboard size={20} /><div><h2>میان برهای صفحه کلید</h2><p>برای کار سریع تر بدون ماوس.</p></div></header><div className="shortcut-list"><span><kbd>Ctrl / Cmd</kbd><kbd>N</kbd><b>محتوای جدید</b></span><span><kbd>Ctrl / Cmd</kbd><kbd>K</kbd><b>جستجوی سراسری</b></span><span><kbd>Esc</kbd><b>بستن پنل</b></span></div></section></div>
    <ReferenceManager open={managerOpen} onClose={() => setManagerOpen(false)} workspace={workspace.data} />
  </div>;
}

function UserManagementPanel() {
  const { hasPermission } = useAuth();
  const { pushToast } = useUIStore();
  const [users, setUsers] = useState<SafeUser[]>([]);
  const [open, setOpen] = useState(false);
  const load = () => void authService.listUsers().then(setUsers);
  useEffect(load, []);
  const disable = async (user: SafeUser) => { await authService.updateUser(user.id, { status: user.status === "ACTIVE" ? "INACTIVE" : "ACTIVE" }); load(); pushToast({ title: "وضعیت کاربر به روز شد." }); };
  return <section className="surface settings-section users-section"><header><Users size={20} /><div><h2>مدیریت کاربران</h2><p>کاربران، نقش ها، Scope داده و وضعیت حساب ها را مدیریت کنید.</p></div></header><div className="user-table">{users.slice(0, 6).map((user) => <div key={user.id}><strong>{user.firstName} {user.lastName}</strong><span>{user.username}</span><small>{user.role} · {user.status}</small>{hasPermission("users.disable") && <Button size="sm" variant="secondary" onClick={() => void disable(user)}>{user.status === "ACTIVE" ? "غیرفعال" : "فعال"}</Button>}</div>)}</div>{users.length === 0 && <p className="form-warning">کاربری برای نمایش وجود ندارد.</p>}<footer className="settings-actions">{hasPermission("users.create") && <Button variant="secondary" onClick={() => setOpen(true)}><Plus size={17} />افزودن کاربر</Button>}</footer><CreateUserDialog open={open} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(); }} /></section>;
}

function CreateUserDialog({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) {
  const { pushToast } = useUIStore();
  const [form, setForm] = useState<CreateUserInput>({ username: "", email: "", firstName: "", lastName: "", phone: "", jobTitle: "", department: "", team: "", role: "USER", extraPermissions: [], dataScope: "OWN", status: "ACTIVE", temporaryPassword: "", mustChangePassword: true, adminNotes: "" });
  const update = <K extends keyof CreateUserInput>(key: K, value: CreateUserInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const create = async () => { try { await authService.createUser(form); pushToast({ title: "کاربر ایجاد شد. رمز موقت فقط همین بار در فرم قابل مشاهده بود." }); onSaved(); } catch (error) { pushToast({ title: error instanceof Error ? error.message : "ایجاد کاربر ممکن نشد." }); } };
  const generatePassword = () => update("temporaryPassword", `Zambil-${crypto.randomUUID().slice(0, 8)}!${Math.floor(Math.random() * 90 + 10)}`);
  return <Dialog open={open} title="افزودن کاربر" description="رمز موقت ذخیره نمی شود و کاربر در اولین ورود مجبور به تغییر آن است." onClose={onClose} wide><div className="form-grid"><Field label="نام"><Input value={form.firstName} onChange={(event) => update("firstName", event.target.value)} /></Field><Field label="نام خانوادگی"><Input value={form.lastName} onChange={(event) => update("lastName", event.target.value)} /></Field><Field label="نام کاربری"><Input value={form.username} onChange={(event) => update("username", event.target.value)} /></Field><Field label="ایمیل"><Input value={form.email} onChange={(event) => update("email", event.target.value)} /></Field><Field label="شماره تماس" optional><Input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></Field><Field label="عنوان شغلی" optional><Input value={form.jobTitle} onChange={(event) => update("jobTitle", event.target.value)} /></Field><Field label="تیم" optional><Input value={form.team} onChange={(event) => update("team", event.target.value)} /></Field><Field label="واحد" optional><Input value={form.department} onChange={(event) => update("department", event.target.value)} /></Field><Field label="نقش"><Select value={form.role} onChange={(event) => update("role", event.target.value as RoleKey)}>{authService.roles().map((role) => <option value={role.key} key={role.key}>{role.label}</option>)}</Select></Field><Field label="Scope داده"><Select value={form.dataScope} onChange={(event) => update("dataScope", event.target.value as DataScope)}>{authService.dataScopes().map((scope) => <option value={scope} key={scope}>{scope}</option>)}</Select></Field><Field label="وضعیت"><Select value={form.status} onChange={(event) => update("status", event.target.value as AccountStatus)}>{(["PENDING", "ACTIVE", "INACTIVE", "LOCKED", "SUSPENDED"] as AccountStatus[]).map((status) => <option value={status} key={status}>{status}</option>)}</Select></Field><Field label="رمز موقت"><div className="password-field"><Input value={form.temporaryPassword} onChange={(event) => update("temporaryPassword", event.target.value)} /><button type="button" onClick={generatePassword}>تولید</button></div></Field></div><footer className="dialog-footer"><Button variant="secondary" onClick={onClose}>انصراف</Button><Button onClick={() => void create()}>ایجاد کاربر</Button></footer></Dialog>;
}

function ReferenceManager({ open, onClose, workspace }: { open: boolean; onClose: () => void; workspace: NonNullable<ReturnType<typeof useWorkspace>["data"]> }) {
  const [kind, setKind] = useState<ReferenceKind>("platform"); const [name, setName] = useState(""); const [color, setColor] = useState("#0f766e"); const queryClient = useQueryClient(); const { pushToast } = useUIStore();
  const data: Record<ReferenceKind, ReferenceEntity[]> = { platform: workspace.platforms, type: workspace.types, status: workspace.statuses, pillar: workspace.pillars, tag: workspace.tags };
  const add = async () => { if (name.trim().length < 2) return; const base = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), archivedAt: null, sortOrder: data[kind].length, version: 1 }; let entity: ReferenceEntity; if (kind === "platform") entity = { ...base, name: name.trim(), color, icon: "Circle", characterLimit: null, preferredTypes: [], defaultPublishingTime: null, notes: null } as Platform; else if (kind === "type") entity = { ...base, name: name.trim(), color, icon: "FileText" } as ContentType; else if (kind === "pillar") entity = { ...base, name: name.trim(), color, description: null } as ContentPillar; else if (kind === "tag") entity = { ...base, name: name.trim(), color } as Tag; else return; await contentRepository.saveReference(kind, entity); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); setName(""); pushToast({ title: "مورد جدید افزوده شد." }); };
  const remove = async (id: string) => { await contentRepository.deleteReference(kind, id); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); pushToast({ title: "مورد حذف شد." }); };
  return <Dialog open={open} title="مدیریت داده های مرجع" description="حذف یک مورد در حال استفاده، داده های محتوای قبلی را تغییر نمی دهد." onClose={onClose} wide><div className="reference-tabs">{(["platform", "type", "status", "pillar", "tag"] as ReferenceKind[]).map((item) => <button type="button" key={item} className={kind === item ? "active" : ""} onClick={() => setKind(item)}>{({ platform: "پلتفرم", type: "نوع", status: "وضعیت", pillar: "ستون", tag: "برچسب" })[item]}</button>)}</div><div className="reference-list">{data[kind].map((item) => <div key={item.id}><span style={{ backgroundColor: item.color }} /><strong>{item.name}</strong>{kind !== "status" && <Button size="sm" variant="danger" onClick={() => void remove(item.id)}>حذف</Button>}</div>)}</div>{kind !== "status" && <div className="reference-add"><input className="input" value={name} onChange={(event) => setName(event.target.value)} placeholder="نام مورد جدید" /><input aria-label="رنگ" className="color-input" type="color" value={color} onChange={(event) => setColor(event.target.value)} /><Button onClick={() => void add()}><Plus size={17} />افزودن</Button></div>}<footer className="dialog-footer"><Button variant="secondary" onClick={onClose}>بستن</Button></footer></Dialog>;
}

function saveFile(name: string, raw: string, type: string) { const url = URL.createObjectURL(new Blob([raw], { type: `${type};charset=utf-8` })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
