import { ArrowLeft, CalendarRange, CopyPlus, Lightbulb, Plus, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { PageHeader } from "../../components/app-shell";
import { Button, Dialog, EmptyState, Field, Select, Textarea } from "../../components/ui";
import { contentRepository } from "../../services/content-repository";
import { scoreIdea } from "../../services/idea-scoring";
import { useWorkspace } from "../../hooks/use-workspace";
import { useUIStore } from "../../stores/ui-store";
import type { Campaign, Content, ContentIdea, ContentTemplate, IdeaScore, Priority } from "../../types/domain";
import { todayIso } from "../../utils/jalali";

const metadata = () => ({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), archivedAt: null, sortOrder: Date.now(), version: 1 });

export function CampaignsPage() {
  const workspace = useWorkspace();
  const [editing, setEditing] = useState<Campaign | null>(null);
  const [creating, setCreating] = useState(false);
  const queryClient = useQueryClient();
  const { pushToast } = useUIStore();
  if (workspace.isLoading) return <PageLoading />;
  if (!workspace.data) return <Unavailable />;
  const save = async (campaign: Campaign) => { await contentRepository.saveCampaign(campaign); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); setCreating(false); setEditing(null); pushToast({ title: "کمپین ذخیره شد." }); };
  return <div className="page"><PageHeader title="کمپین ها" description="هدف، بازه زمانی و خروجی های هر حرکت محتوایی را در یک جا نگه دارید." actions={<Button onClick={() => setCreating(true)}><Plus size={18} />کمپین جدید</Button>} />
    <section className="entity-grid">{workspace.data.campaigns.filter((item) => !item.archivedAt).map((campaign) => { const related = workspace.data.contents.filter((content) => content.campaignId === campaign.id); const published = related.filter((content) => content.status === "published").length; return <button className="entity-card campaign-card" type="button" onClick={() => setEditing(campaign)} key={campaign.id}><span className={`campaign-state ${campaign.status}`}>{({ draft: "پیش نویس", active: "فعال", completed: "تمام شده", archived: "بایگانی" })[campaign.status]}</span><h2>{campaign.title}</h2><p>{campaign.goal || "هدف این کمپین هنوز مشخص نشده است."}</p><div className="entity-meta"><span><CalendarRange size={16} />{campaign.startDate ? `${campaign.startDate} تا ${campaign.endDate ?? "-"}` : "بدون بازه"}</span><span>{published.toLocaleString("fa-IR")} از {related.length.toLocaleString("fa-IR")} منتشر شده</span></div><div className="progress-track"><span style={{ width: `${related.length ? Math.round((published / related.length) * 100) : 0}%` }} /></div></button>; })}{workspace.data.campaigns.length === 0 && <EmptyState title="کمپینی ندارید" description="کمپین ها برای پیگیری یک هدف و مجموعه ای از محتوا به کار می روند." action={<Button size="sm" onClick={() => setCreating(true)}><Plus size={16} />ساخت کمپین</Button>} />}</section>
    <CampaignDialog open={creating || Boolean(editing)} campaign={editing} onClose={() => { setCreating(false); setEditing(null); }} onSave={save} />
  </div>;
}

function CampaignDialog({ open, campaign, onClose, onSave }: { open: boolean; campaign: Campaign | null; onClose: () => void; onSave: (campaign: Campaign) => Promise<void> }) {
  const [title, setTitle] = useState(campaign?.title ?? ""); const [goal, setGoal] = useState(campaign?.goal ?? ""); const [description, setDescription] = useState(campaign?.description ?? ""); const [startDate, setStartDate] = useState(campaign?.startDate ?? ""); const [endDate, setEndDate] = useState(campaign?.endDate ?? ""); const [status, setStatus] = useState<Campaign["status"]>(campaign?.status ?? "draft");
  const persist = async () => { if (title.trim().length < 2) return; await onSave({ ...(campaign ?? metadata()), title: title.trim(), goal: goal.trim() || null, description: description.trim() || null, startDate: startDate || null, endDate: endDate || null, platformIds: campaign?.platformIds ?? [], targetAudience: campaign?.targetAudience ?? null, mainMessage: campaign?.mainMessage ?? null, kpi: campaign?.kpi ?? null, status, notes: campaign?.notes ?? null }); };
  return <Dialog open={open} title={campaign ? "ویرایش کمپین" : "کمپین جدید"} onClose={onClose}><div className="form-grid"><Field label="عنوان کمپین"><input className="input" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="وضعیت"><Select value={status} onChange={(event) => setStatus(event.target.value as Campaign["status"])}><option value="draft">پیش نویس</option><option value="active">فعال</option><option value="completed">تمام شده</option></Select></Field><Field label="هدف" optional><input className="input" value={goal ?? ""} onChange={(event) => setGoal(event.target.value)} /></Field><Field label="تاریخ شروع" optional><input className="input ltr-input" type="date" value={startDate ?? ""} onChange={(event) => setStartDate(event.target.value)} /></Field><Field label="تاریخ پایان" optional><input className="input ltr-input" type="date" value={endDate ?? ""} onChange={(event) => setEndDate(event.target.value)} /></Field><Field label="توضیحات" optional><Textarea rows={4} value={description ?? ""} onChange={(event) => setDescription(event.target.value)} /></Field></div><footer className="dialog-footer"><Button variant="secondary" onClick={onClose}>انصراف</Button><Button onClick={() => void persist()}>ذخیره کمپین</Button></footer></Dialog>;
}

export function IdeasPage() {
  const workspace = useWorkspace(); const [editing, setEditing] = useState<ContentIdea | null>(null); const [creating, setCreating] = useState(false); const queryClient = useQueryClient(); const { pushToast } = useUIStore();
  if (workspace.isLoading) return <PageLoading />; if (!workspace.data) return <Unavailable />;
  const save = async (idea: ContentIdea) => { const scoredIdea = { ...idea, score: scoreIdea(idea) }; await contentRepository.saveIdea(scoredIdea); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); setCreating(false); setEditing(null); pushToast({ title: `ایده با نمره ${scoredIdea.score.total.toLocaleString("fa-IR")} ذخیره شد.` }); };
  const convert = async (idea: ContentIdea) => { const platformId = workspace.data?.platforms[0]?.id; const typeId = workspace.data?.types[0]?.id; if (!platformId || !typeId) return; const content: Content = { ...metadata(), title: idea.title, shortDescription: idea.description ?? null, brief: idea.notes ?? null, typeId, platformId, campaignId: null, pillarId: idea.pillarId ?? null, tagIds: idea.tagIds, owner: null, reviewer: null, publisher: null, priority: idea.priority, status: "draft", publicationDate: todayIso(), publicationTime: null, timezone: "Asia/Tehran", startDate: null, deadline: null, productionDate: null, reviewDate: null, recurrence: null, caption: null, mainCopy: null, hook: null, callToAction: null, hashtags: null, keywords: null, link: idea.referenceLink ?? null, sourceLink: null, notes: idea.notes ?? null, checklist: [], attachments: [], contentVersion: 1, performance: null }; await contentRepository.saveContent(content); await contentRepository.deleteEntity("idea", idea.id); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); await queryClient.invalidateQueries({ queryKey: ["contents"] }); pushToast({ title: "ایده به یک محتوای پیش نویس تبدیل شد." }); };
  return <div className="page"><PageHeader title="ایده ها" description="ایده ها با اصول Playbook زمبیل نمره می گیرند: capture، فروشنده، اعتماد، تکرار خرید و سنجش پذیری." actions={<Button onClick={() => setCreating(true)}><Plus size={18} />ایده جدید</Button>} /><section className="idea-grid">{workspace.data.ideas.filter((item) => !item.archivedAt).map((idea) => { const score = idea.score ?? scoreIdea(idea); return <article className="idea-card" key={idea.id}><div><span className={`priority-dot ${idea.priority}`} />{({ low: "کم", normal: "عادی", high: "زیاد", urgent: "فوری" })[idea.priority]}</div><div className="idea-score-head"><h2>{idea.title}</h2><ScorePill score={score} /></div><p>{idea.description || "توضیحات بیشتری برای این ایده ثبت نشده است."}</p><IdeaScoreSummary score={score} /><footer><Button size="sm" variant="secondary" onClick={() => setEditing(idea)}>ویرایش</Button><Button size="sm" onClick={() => void convert(idea)}><ArrowLeft size={16} />تبدیل به محتوا</Button></footer></article>; })}{workspace.data.ideas.length === 0 && <EmptyState title="ایده ای ثبت نشده است" description="ایده های خام را این جا نگه دارید تا زمان مناسب برای تولیدشان برسد." action={<Button size="sm" onClick={() => setCreating(true)}><Lightbulb size={16} />افزودن ایده</Button>} />}</section><IdeaDialog open={creating || Boolean(editing)} idea={editing} onClose={() => { setCreating(false); setEditing(null); }} onSave={save} /></div>;
}

function IdeaDialog({ open, idea, onClose, onSave }: { open: boolean; idea: ContentIdea | null; onClose: () => void; onSave: (idea: ContentIdea) => Promise<void> }) { const [title, setTitle] = useState(idea?.title ?? ""); const [description, setDescription] = useState(idea?.description ?? ""); const [priority, setPriority] = useState<Priority>(idea?.priority ?? "normal"); const [notes, setNotes] = useState(idea?.notes ?? ""); useEffect(() => { if (!open) return; setTitle(idea?.title ?? ""); setDescription(idea?.description ?? ""); setPriority(idea?.priority ?? "normal"); setNotes(idea?.notes ?? ""); }, [idea, open]); const liveScore = useMemo(() => scoreIdea({ title, description, notes, priority }), [description, notes, priority, title]); const persist = async () => { if (title.trim().length < 2) return; await onSave({ ...(idea ?? metadata()), title: title.trim(), description: description.trim() || null, priority, notes: notes.trim() || null, tagIds: idea?.tagIds ?? [], pillarId: idea?.pillarId ?? null, referenceLink: idea?.referenceLink ?? null, score: liveScore }); }; return <Dialog open={open} title={idea ? "ویرایش ایده" : "ایده جدید"} onClose={onClose}><div className="form-grid"><Field label="عنوان ایده"><input className="input" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="اولویت"><Select value={priority} onChange={(event) => setPriority(event.target.value as Priority)}><option value="low">کم</option><option value="normal">عادی</option><option value="high">زیاد</option><option value="urgent">فوری</option></Select></Field><Field label="توضیح" optional><Textarea rows={4} value={description ?? ""} onChange={(event) => setDescription(event.target.value)} /></Field><Field label="یادداشت" optional><Textarea rows={4} value={notes ?? ""} onChange={(event) => setNotes(event.target.value)} /></Field><div className="idea-score-panel"><header><Sparkles size={18} /><div><strong>نمره ایده</strong><span>{liveScore.summary}</span></div><ScorePill score={liveScore} /></header><IdeaScoreSummary score={liveScore} detailed /></div></div><footer className="dialog-footer"><Button variant="secondary" onClick={onClose}>انصراف</Button><Button onClick={() => void persist()}>ذخیره ایده</Button></footer></Dialog>; }

function ScorePill({ score }: { score: IdeaScore }) {
  return <span className="score-pill" data-score={score.label}>{score.total.toLocaleString("fa-IR")}<small>/۱۰۰</small></span>;
}

function IdeaScoreSummary({ score, detailed = false }: { score: IdeaScore; detailed?: boolean }) {
  return <div className="idea-score-summary"><div className="score-track"><span style={{ width: `${score.total}%` }} /></div><p>{score.summary}</p>{score.strengths.length > 0 && <div className="score-tags">{score.strengths.map((item) => <span key={item}>{item}</span>)}</div>}{detailed && <ul>{score.recommendations.map((item) => <li key={item}>{item}</li>)}</ul>}</div>;
}

export function TemplatesPage() {
  const workspace = useWorkspace(); const [editing, setEditing] = useState<ContentTemplate | null>(null); const [creating, setCreating] = useState(false); const queryClient = useQueryClient(); const { pushToast, openContentDialog } = useUIStore();
  if (workspace.isLoading) return <PageLoading />; if (!workspace.data) return <Unavailable />;
  const save = async (template: ContentTemplate) => { await contentRepository.saveTemplate(template); await queryClient.invalidateQueries({ queryKey: ["workspace"] }); setCreating(false); setEditing(null); pushToast({ title: "قالب ذخیره شد." }); };
  return <div className="page"><PageHeader title="قالب ها" description="برای ساخت سریع تر محتواهای تکراری، چارچوب های آماده بسازید." actions={<Button onClick={() => setCreating(true)}><Plus size={18} />قالب جدید</Button>} /><section className="entity-grid">{workspace.data.templates.filter((item) => !item.archivedAt).map((template) => <article className="entity-card template-card" key={template.id}><CopyPlus size={22} /><h2>{template.title}</h2><p>{template.brief || "بدون توضیح پیش فرض"}</p><div className="entity-meta"><span>{workspace.data.platforms.find((item) => item.id === template.platformId)?.name ?? "همه پلتفرم ها"}</span><span>{workspace.data.types.find((item) => item.id === template.typeId)?.name ?? "همه نوع ها"}</span></div><footer><Button size="sm" variant="secondary" onClick={() => setEditing(template)}>ویرایش</Button><Button size="sm" onClick={() => openContentDialog({ quick: false })}>استفاده</Button></footer></article>)}{workspace.data.templates.length === 0 && <EmptyState title="قالبی ندارید" description="قالب ها بخش های تکراری کار را از مسیر شما کنار می زنند." action={<Button size="sm" onClick={() => setCreating(true)}><Plus size={16} />ساخت قالب</Button>} />}</section><TemplateDialog open={creating || Boolean(editing)} template={editing} workspace={workspace.data} onClose={() => { setCreating(false); setEditing(null); }} onSave={save} /></div>;
}

function TemplateDialog({ open, template, workspace, onClose, onSave }: { open: boolean; template: ContentTemplate | null; workspace: NonNullable<ReturnType<typeof useWorkspace>["data"]>; onClose: () => void; onSave: (template: ContentTemplate) => Promise<void> }) { const [title, setTitle] = useState(template?.title ?? ""); const [platformId, setPlatformId] = useState(template?.platformId ?? ""); const [typeId, setTypeId] = useState(template?.typeId ?? ""); const [brief, setBrief] = useState(template?.brief ?? ""); const persist = async () => { if (title.trim().length < 2) return; await onSave({ ...(template ?? metadata()), title: title.trim(), platformId: platformId || null, typeId: typeId || null, brief: brief.trim() || null, captionStructure: template?.captionStructure ?? null, checklist: template?.checklist ?? [], defaultStatus: template?.defaultStatus ?? "draft", defaultOwner: template?.defaultOwner ?? null, defaultTagIds: template?.defaultTagIds ?? [], defaultPublishingTime: template?.defaultPublishingTime ?? null }); }; return <Dialog open={open} title={template ? "ویرایش قالب" : "قالب جدید"} onClose={onClose}><div className="form-grid"><Field label="عنوان قالب"><input className="input" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></Field><Field label="پلتفرم پیش فرض" optional><Select value={platformId ?? ""} onChange={(event) => setPlatformId(event.target.value)}><option value="">همه پلتفرم ها</option>{workspace.platforms.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select></Field><Field label="نوع پیش فرض" optional><Select value={typeId ?? ""} onChange={(event) => setTypeId(event.target.value)}><option value="">همه نوع ها</option>{workspace.types.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select></Field><Field label="خلاصه پیش فرض" optional><Textarea rows={4} value={brief ?? ""} onChange={(event) => setBrief(event.target.value)} /></Field></div><footer className="dialog-footer"><Button variant="secondary" onClick={onClose}>انصراف</Button><Button onClick={() => void persist()}>ذخیره قالب</Button></footer></Dialog>; }

function PageLoading() { return <div className="page"><div className="skeleton heading-skeleton" /><div className="skeleton panel-skeleton" /></div>; }
function Unavailable() { return <div className="page"><EmptyState title="داده ها در دسترس نیستند" description="فضای کاری را دوباره باز کنید." /></div>; }
