import { BarChart3, Download, FileText, Printer, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeader } from "../../components/app-shell";
import { Button, EmptyState, Field, Input, Select, StatusBadge } from "../../components/ui";
import { STATUS_META } from "@shared/constants/defaults";
import { useContents, useWorkspace } from "../../hooks/use-workspace";
import { useUIStore } from "../../stores/ui-store";
import { formatJalaliDate, parseJalaliDate, toPersianDigits } from "@shared/utils/jalali";

export function ReportsPage() {
  const workspace = useWorkspace(); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [platformId, setPlatformId] = useState(""); const { pushToast } = useUIStore();
  const fromDate = from ? parseJalaliDate(from) ?? undefined : undefined; const toDate = to ? parseJalaliDate(to) ?? undefined : undefined;
  const contents = useContents({ fromDate, toDate, platformIds: platformId ? [platformId] : undefined });
  const stats = useMemo(() => { const data = contents.data ?? []; const count = (predicate: (value: typeof data[number]) => boolean) => data.filter(predicate).length; return { total: data.length, published: count((item) => item.status === "published"), scheduled: count((item) => item.status === "scheduled"), missed: count((item) => Boolean(item.deadline && item.deadline < new Date().toISOString().slice(0, 10) && item.status !== "published")), status: Object.keys(STATUS_META).map((key) => [key, count((item) => item.status === key)] as const).filter(([, value]) => value > 0), platforms: workspace.data?.platforms.map((platform) => [platform.name, count((item) => item.platformId === platform.id)] as const).filter(([, value]) => value > 0) ?? [], pillars: workspace.data?.pillars.map((pillar) => [pillar.name, count((item) => item.pillarId === pillar.id)] as const).filter(([, value]) => value > 0) ?? [] }; }, [contents.data, workspace.data]);
  if (workspace.isLoading || contents.isLoading) return <div className="page"><div className="skeleton heading-skeleton" /><div className="skeleton panel-skeleton" /></div>;
  if (!workspace.data) return <div className="page"><EmptyState title="گزارش در دسترس نیست" description="فضای کاری را دوباره باز کنید." /></div>;
  const exportReport = () => { const rows = ["عنوان,تاریخ,پلتفرم,وضعیت", ...(contents.data ?? []).map((item) => `"${item.title.replaceAll('"', '""')}",${item.publicationDate},"${workspace.data?.platforms.find((platform) => platform.id === item.platformId)?.name ?? ""}","${STATUS_META[item.status].label}"`)]; const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8" })); anchor.download = "rooznegar-report.csv"; anchor.click(); URL.revokeObjectURL(anchor.href); pushToast({ title: "گزارش CSV آماده شد." }); };
  return <div className="page reports-page"><PageHeader title="گزارش ها" description="تصمیم های برنامه ریزی را با وضعیت واقعی محتوا بگیرید." actions={<><Button variant="secondary" onClick={() => window.print()}><Printer size={17} />چاپ</Button><Button onClick={exportReport}><Download size={17} />CSV</Button></>} />
    <section className="filter-bar surface report-filters"><Field label="از تاریخ جلالی" optional><Input value={from} onChange={(event) => setFrom(event.target.value)} placeholder="۱۴۰۵/۰۴/۰۱" /></Field><Field label="تا تاریخ جلالی" optional><Input value={to} onChange={(event) => setTo(event.target.value)} placeholder="۱۴۰۵/۰۴/۳۱" /></Field><Field label="پلتفرم" optional><Select value={platformId} onChange={(event) => setPlatformId(event.target.value)}><option value="">همه پلتفرم ها</option>{workspace.data.platforms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field></section>
    {((from && !fromDate) || (to && !toDate)) && <p className="form-warning">تاریخ را به شکل ۱۴۰۵/۰۴/۰۱ وارد کنید.</p>}
    <section className="metric-grid"><Metric icon={<FileText />} label="کل محتوای بازه" value={stats.total} tone="teal" /><Metric icon={<TrendingUp />} label="منتشر شده" value={stats.published} tone="green" /><Metric icon={<BarChart3 />} label="زمان بندی شده" value={stats.scheduled} tone="violet" /><Metric icon={<FileText />} label="مهلت های از دست رفته" value={stats.missed} tone="red" /></section>
    {stats.total ? <section className="report-grid"><Breakdown title="توزیع وضعیت" values={stats.status.map(([key, value]) => ({ label: STATUS_META[key as keyof typeof STATUS_META].label, value, color: STATUS_META[key as keyof typeof STATUS_META].color }))} /><Breakdown title="توزیع پلتفرم" values={stats.platforms.map(([label, value], index) => ({ label, value, color: ["#0f766e", "#2563eb", "#b45309", "#7c3aed"][index % 4] }))} /><Breakdown title="توزیع ستون محتوا" values={stats.pillars.map(([label, value], index) => ({ label, value, color: ["#be123c", "#0369a1", "#15803d", "#a16207"][index % 4] }))} /><section className="surface report-list"><h2>خلاصه انتشار</h2>{contents.data?.slice(0, 6).map((item) => <div key={item.id}><span>{formatJalaliDate(item.publicationDate)}</span><strong>{item.title}</strong><StatusBadge status={item.status} label={STATUS_META[item.status].label} color={STATUS_META[item.status].color} /></div>)}</section></section> : <EmptyState title="داده ای برای گزارش وجود ندارد" description="بازه یا فیلتر را تغییر دهید، یا ابتدا چند محتوا در تقویم بسازید." />}
  </div>;
}

function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: number; tone: string }) { return <section className={`metric metric-${tone}`}><span>{icon}</span><div><strong>{toPersianDigits(value)}</strong><p>{label}</p></div></section>; }
function Breakdown({ title, values }: { title: string; values: { label: string; value: number; color: string }[] }) { const total = values.reduce((sum, item) => sum + item.value, 0); return <section className="surface breakdown"><h2>{title}</h2>{values.length ? values.map((item) => <div className="breakdown-row" key={item.label}><div><span style={{ backgroundColor: item.color }} />{item.label}</div><strong>{toPersianDigits(item.value)}</strong><div className="breakdown-track"><span style={{ width: `${total ? Math.round((item.value / total) * 100) : 0}%`, backgroundColor: item.color }} /></div></div>) : <p>داده ای ثبت نشده است.</p>}</section>; }
